### ISSUE TITLE
Client-side crash upon entering Nether

### ISSUE THREAD

**Issue by AegisInquisitor** [AjaxVM/peaceful-carnage-modpack#113]
I had already gone into the Nether once, and had just come out of it. Was crafting some tools and whatnot, went back through portal and game crashed without a crashlog.

Final entry in the regular logs:

[00:19:44] [main/WARN]: Received passengers for unknown entity

Edit: After rejoining server, I ended up hundreds of blocks away from the portal, inside the Nether, way above ground, nonetheless.

**Comment by AjaxVM** [comment]
Passenger for unknown entity - but just a warn so probably not the issue... I dunno...
I'll look at the logs more in depth later tonight

**Comment by AegisInquisitor** [comment]
Yeah, not a huge deal either - just odd that the server translated it into "Oh hey, lets move him way away from where he came in..."

**Comment by AjaxVM** [comment]
I think this might be an artifact of upgrading a 0.6 world to 0.7 - let's rebug if we can reproduce on a fresh world...
