### ISSUE TITLE
Dying with armor on

### ISSUE THREAD

**Issue by AegisInquisitor** [AjaxVM/peaceful-carnage-modpack#30]
Died with armor from fall damage, when I respawned the armor still functioned on me (visbily above health bar) although I was not wearing the armor.

**Comment by AjaxVM** [comment]
Haha nice - any idea which mod might be causing? did you see if you still had armor or if it was just a visual relic?

**Comment by AegisInquisitor** [comment]
Yeah, I went to a zombie and only took a heart of a damage, I was still affected by it. I can try to reproduce it, but if I had to guess I'd say probably the gravestone mod working oddly with not dropping items maybe.

**Comment by AjaxVM** [comment]
This has not been reproduced in a while - going to close for now.
