### ISSUE TITLE
[Suggestion] Iron Backpacks Upgrades

### ISSUE THREAD

**Issue by AegisInquisitor** [AjaxVM/peaceful-carnage-modpack#31]
The Iron Backpacks mod usually comes with upgrades, though I can't find them in-game (either with JEI or with manual crafting), so I assume they're turned off - some of them are obviously fairly powerful and I don't mind those ones being disabled, though some can be very useful for just quality of life upgrades, such as the compression upgrade, which auto compresses the items you pick up (9 coal - 1 coal block, etc).

Just a thought, trying to help out where I can.

-Edit: I'd also be just as happy if we could open the backpack directly from our inventories, rather than having to throw them on the hotbar each time, which fills up quickly.

**Comment by JustThePacksTeam** [comment]
Helps if u read the wiki. they arent in yet. Be graeteful u have bags

**Comment by AegisInquisitor** [comment]
@JustThePacksTeam No need to be rude. I did in fact read the wiki, although I must have missed that, which was my mistake.
