### ISSUE TITLE
Tinker's Hatchet + TreeCap

### ISSUE THREAD

**Issue by AegisInquisitor** [AjaxVM/peaceful-carnage-modpack#32]
Tinker's Hatchets will not gain experience from felling trees with TreeCap (or whatever the current mod is), tested with just breaking one block via crouch/break and it granted experience as normal, could require some config to fix this although it is quite annoying.

**Comment by BlueSilverXIII** [comment]
technically its not the tinker's axe thats breaking the entire tree so it wouldnt give exp except for the main block your breaking. maybe we can use this as an incentive to actually craft a lumber axe?!?

**Comment by AegisInquisitor** [comment]
IIRC, it wasn't giving xp even for the first block.

Perhaps this would be a good argument for Vein Miner which actually uses the tool/enchantments/etc. to break the connected blocks.

**Comment by AjaxVM** [comment]
VeinMiner has not been updated to 1.12.2 - and would need to see if we can configure it not to actually be used for mining. Personally, I don't see a ton of use for the hatchet in general - even if we disable vanilla tools > stone, most trees (are there any?) don't require more than stone to chop them down effectively. The alternative is to just remove tree chopper and say "use lumberjack axe"

**Comment by AjaxVM** [comment]
Hmm, it is showing updated in Twitch, just not in curse... will explore.

**Comment by AegisInquisitor** [comment]
You certainly can configure it to not be used for mining, you could also configure a hoe to be able to vein mine obsidian xD

But yeah, I don't know about whether it's updated or not. The version I have downloaded is apparently 1.12, not 1.12.2, which will boot up fine on .2 but doesn't seem to be effective.

**Comment by AjaxVM** [comment]
I am looking at veinminer and more considering just removing autochop - incentive to use lumberjack as Blue said...
