### ISSUE TITLE
[Suggestion] Remove animania

### ISSUE THREAD

**Issue by AjaxVM** [AjaxVM/peaceful-carnage-modpack#42]
Some like it, others don't - let's track the discussion here

**Comment by Emimori** [comment]
It's good for variety and taking care of animals presents a challenge for peaceful players that isn't just farming crops or building.

Suggest removing meat drops if at all possible as an alternative.

**Comment by AjaxVM** [comment]
Wow there are a lot of configs we'll need to look at for next version for animania - we can disable the random meat drops - which is nice.
