### ISSUE TITLE
(Mod Suggestion) Deep Resonance

### ISSUE THREAD

**Issue by Joewiibox** [AjaxVM/peaceful-carnage-modpack#53]
https://minecraft.curseforge.com/projects/deep-resonance

Deep Resonance is a power generation mod for Minecraft meant for both early game power as well as high end and more complicated end game power. This release adds oregen (the resonating ore as well as crystals) so that people can put it in their worlds already. It also has a (default disabled) retrogen option for existing worlds. In the current state of the mod you can produce crystals that give 20000 RF/tick for a total of 1 billion RF. But note that getting to that stage is not going to be easy!

**Comment by AjaxVM** [comment]
Until we have more of a use for power (and if we go the RF route) I don't see this fitting in the pack. Probably more a tech-focused expansion or something :D
