### ISSUE TITLE
Add some more transportation/flight

### ISSUE THREAD

**Issue by AjaxVM** [AjaxVM/peaceful-carnage-modpack#63]

**Comment by BlueSilverXIII** [comment]
So far botania's tiara has flight that makes you work for it. 
The other one is voidcraft's xia's armor dropped from the 2nd to the last boss i think. This one gives you unlimited flight as long as you are wearing any of the 4 pieces of armor.

**Comment by AjaxVM** [comment]
Is the tiara still like 30 second max at a time?
Xia's is apparently necessary for the final form fight with Xia so might need to see what to do with that later...

**Comment by BlueSilverXIII** [comment]
Tiara works as long as you have mana on a tablet or band of man. or a mirror attached to a pool. this is pretty much an endgame item.
you need to beat Xia to get the armor which is pretty much an endgame boss from voidcraft. it takes alot of work to get to it.

edit
ok so the tiara does have a cool down when flying. its covered by the shields on top of the hunger bar. it does last a bit longer than 30 sec.
